# Add file paths for your city boundary, origin blocks, and destinations. Enter False in all fields if data already exists on the SQL database
set_up:
  # for US cities use 4269, NZ cities use 4326, otherwise use whatever the origin blocks has been projected in
  projection: 4326
  # Use a seperate file for each dest type, use the same order as 'services' below
  destination_file_directory:
    - /homedirs/projects/x-minute-city/data/raw/Pharmacies2017_points.csv
    # - /homedirs/projects/x-minute-city/data/raw/Hospitals2017_points.shp
    # - /homedirs/projects/x-minute-city/data/raw/Community_oralhealthcare_services.csv
    - /homedirs/projects/x-minute-city/data/raw/All_GP_including_VLCA.csv
    # - /homedirs/projects/x-minute-city/data/raw/Alcohol_outlets_GHL.shp
    # - /homedirs/projects/x-minute-city/data/raw/Dairy_and_conv.shp
    # - /homedirs/projects/x-minute-city/data/raw/Fast_food.shp
    # - /homedirs/projects/x-minute-city/data/raw/Fruit_and_veg.shp
    - /homedirs/projects/x-minute-city/data/raw/supermarket.csv
    # - /homedirs/projects/x-minute-city/data/raw/Takeaways.shp
    # - /homedirs/projects/x-minute-city/data/raw/banks.shp
    # - /homedirs/projects/x-minute-city/data/raw/cafe.shp
    - /homedirs/projects/x-minute-city/data/raw/ece.shp
    - /homedirs/projects/x-minute-city/data/raw/greenspace_point.shp
    - /homedirs/projects/x-minute-city/data/raw/school_primary.csv
    # - /homedirs/projects/x-minute-city/data/raw/worship.shp
  # name of column in shapefile to keep for matching with destination data
  # dest_id_colname:
  #   - OBJECTID
  #   - OBJECTID
  #   - Street_Add
  #   - OBJECTID
  #   - OBJECTID
  #   - FID_
  #   - FID_
  #   - FID_
  #   - index
  #   - FID_
  #   - index
  #   - index
  #   - ECE_Id
  #   - index
  #   - OBJECTID
    # - index
  origin_file_directory: /homedirs/projects/access_nz/data/raw/combined_2018_census.shp
orig_id: SA12018_V1

# Which services do you want to evalaute? (must match 'dest_type' name from destination matix, unless script_mode='setup') TYPE: lst of str's
services:
  - pharmacy
  # - hospital
  # - oral_health
  - doctor
  # - alcohol_outlet
  # - convenience_store
  # - fast_food
  # - fruit_store
  - supermarket
  # - takeaway
  # - bank
  # - cafe
  - ece
  - greenspace
  - primary_school
  # - worship

# Do the destinations or origins need to be initialised?
init:
  dests: False
  origins: False

alter_results:
  drop_blocks: ['7022480', '7001121', '7001125', '7001123', '7023238', '7029871','7002089','7025531','7026226','7026225','7026314','7026512','7026315','7024296','7024652','7024605', '7021150', '7021151', '7022138', '7007859']
  alter_block_results: False


# What mode of transport are you evaluating? ['driving', 'walking', 'cycling'] TYPE: str
transport_mode: ['driving', 'walking', 'cycling']

# What metric would you like to evaluate? comment one out, leaving in list TYPE: str
metric:
 # - distance
  - duration

# This filters origin destination pairs based on their Euclidean proximity and then calculates the network distance between those subset pairs
query_euclidean: True

euclidean_buffer:
  distance: 10000
  max_dests: 15

# What percent of CPU cores would you like to utilise? [0.0 - 1.0] TYPE: float
par_frac: 0.8

# What name would save the distance matrix as? TYPE: str
SQL:
  create_db: True
  database_name: x-minute-city # this is the name of the database
  table_name: durations # this is the name for the table of distances/durations
  port: '5002'
  host: encivmu-tml62


location:
    city: New Zealand
    city_code: nz
    # State code (e.g. 'wa' for Washington, Seattle), this selects the SQL database, 'access_{state}' TYPE: str
    state: nz
    country: nz

# For logging information and downloading the latest OSM data (Check osm_region/osm_subregion for the osm.pbf download link from https://download.geofabrik.de/north-america/us.html) TYPE: str
OSM:
    osm_subregion: new-zealand
    osm_region: australia-oceania
    # where do you want your OSM data saved
    data_directory: '/home/mitchell/projects/x-minute-city/data/osm'

OSRM:
    host: http://localhost
    port: '6004'
    # Do you want the port closed after use? [True, False] TYPE: bool
    shutdown: True


data_export:
  execute: True
  block_results: False
  block_shapefile: False
  block_topojson: False
  region_centroids: False
  region_destinations: False
  access_histogram: False
  edes: True
  percent_stats: True
  git_push: True
  rankings: False
